export const DetailListItemFields = [{
  key: 'title',
  label: 'Title',
  placeholder: 'title',
  type: 'text'
}, {
  key: 'institution',
  label: 'Institution',
  placeholder: 'institution',
  type: 'text'
}, {
  key: 'link',
  label: 'Link',
  placeholder: 'link',
  type: 'text'
}, {
  key: 'location',
  label: 'Location',
  placeholder: 'Location',
  type: 'text'
}, {
  key: 'start',
  label: 'Start',
  placeholder: 'Start',
  type: 'month'
}, {
  key: 'end',
  label: 'End',
  placeholder: 'End',
  type: 'month'
}, {
  key: 'description',
  label: 'Description',
  placeholder: 'Description',
  type: 'textarea'
}, {
  key: 'tags',
  label: 'Tags',
  placeholder: 'Tags',
  type: 'text'
}];
